### ISSUE TITLE
Keymaps

### ISSUE THREAD

**Issue by mb720** [Cloudef/bemenu#104]
Hi!

I was wondering if it's possible in bemenu to define keymaps. Specifically I'd like to select the next entry in bemenu's list with `control + l` instead of the right arrow key, for example.

Is this configurable?

**Comment by Cloudef** [comment]
Nope this is not configurable. This would need some major restructuring too do be able to do sanely.

**Comment by Cloudef** [comment]
That said, if you are not afraid of modifying the code itself. It's pretty trivial to do this then. For example if you use X11, you could modify this switch statement here to your liking https://github.com/Cloudef/bemenu/blob/master/lib/renderers/x11/x11.c#L52-L153 wayland and curses have similar switch statement in them. Creating patch from your modification also is unlikely to break since these code paths don't change often.
