### ISSUE TITLE
How to change the colour of the cursor and allow left right arrow keys to work?

### ISSUE THREAD

**Issue by aryabhatta-dey** [Cloudef/bemenu#118]
System: Arch Linux, sway, bemenu v:0.4.0-1 with bemenu-wlroots backend installed from the official repo

Problem: I would like to either black out the cursor or remove it. I liked the previous look where there was no cursor. Could not figure out how to change it's color. Also before the last update the left right arrow keys used to work to move between selection items. Now only up down arrow keys work. Can I change it?

I am invoking bemenu using bemenu -n -i -I=1 -fn "SourceCodePro-Medium.otf" -p "Clipboard" --tf=#E7CA9C  --hf=#dadee0 --nf=#6a7e95

**Comment by Cloudef** [comment]
The left/right now always move cursor since the addition of visible cursor. You can use shift + left / right to move selection.
https://github.com/Cloudef/bemenu/commit/fcce2e019aedf1e34002796cb567deb958926d7d

There is no option to disable or color the cursor as for now. The cursor works like in terminals usually, inverting the color. If you don't mind patching the code, you can set this line to false https://github.com/Cloudef/bemenu/blob/master/lib/renderers/cairo.h#L246

**Comment by aryabhatta-dey** [comment]
Thank you. 
Do you think a feature to change the look of the cursor can be added? Like the size of the block?

**Comment by Cloudef** [comment]
If you have ideas for different looks, I can consider it. Even better if you can do PR for it, in which case it's likely it'll be merged in.

**Comment by aryabhatta-dey** [comment]
Understood:) Thank you! If I can come up with anything I will
