### ISSUE TITLE
The ability to paste in X11 and Wayland mode is missing.

### ISSUE THREAD

**Issue by Earnestly** [Cloudef/bemenu#12]
It's possible to paste in the curses backend thanks to the terminal emulator via either shift-insert or its pasting mechanism but this functionality is not yet available in X11 or Wayland mode.

For comparison, `dmenu` uses `C-y` for pasting from X11's primary selection buffer.

**Comment by ssiyad** [comment]
Any update on this?

**Comment by rieje** [comment]
Just curious--is there a significant limitation with the way Wayland works for this to be implemented or is there a decent workaround? Would be useful to paste in argument for a command. I thought for sure my clipboard solution for Wayland was inadequate but realized the feature from dmenu is not available.

**Comment by crocket** [comment]
Lack of clipboard support is the single reason that I use terminal backend instead of wayland backend.

**Comment by rieje** [comment]
How does terminal backend work? On my terminal, echo `"hey" | BEMENU_BACKEND=curse bemenu` does nothing.

**Comment by Cloudef** [comment]
@rieje Should be `BEMENU_BACKEND=curses`

**Comment by rieje** [comment]
I tried ncurses backend and it honestly doesn't seem too bad except for lack of support for default bindings (I assume terminal overrides it and not worth giving up those bindings for one application) and fixed size if window (doesn't narrow as items get filtered).

I'm having trouble launching applications with the following command that works in default backend though: `printf '%s\n' "$selection" | ${SHELL:-"/bin/sh"} &`, which is how `dmenu_run` executes commands. I guess the problems described below has to do with detaching?:

* When executing the bemenu script in terminal (this issue is not important, as bemenu should mostly be run via keybinding, so feel free to skip to the next point), it will execute the selected item, but if the item is a command that doesn't exit (like Firefox) then you see all the background stuff you normally see when running a GUI from the terminal. I prefer it to exit the terminal when Firefox started, like a traditional app launcher (or how dmenu/bemenu behaves where it just exits after item is selected).

* When executed via keybinding, it starts a terminal, runs the bemenu script, but exits the both it and the terminal after selection is made, without executing the selection or doing anything.

With printf '%s\n' "$selection" | ${SHELL:-"/bin/sh"}` instead:
* In terminal, save behavior as before.
* Via keybinding, it starts the terminal, executes the selected item, and terminates the terminal that started bemenu immediately, resulting in the traditional and desired behavior of an app launcher. But when launching Firefox (or GUI programs that don't exit until the program is closed), you will again see the background stuff in the open terminal. Exiting Firefox closes this terminal.

**Comment by Cloudef** [comment]
You probably want to use the `--fork` option with bemenu-run if you don't want command to be executed inside the shell.

**Comment by rieje** [comment]
Hmm, getting closer. With `BEMENU_BACKEND=curses /usr/bin/bemenu --fork` and bemenu script with `printf '%s\n' "$selection" | ${SHELL:-"/bin/sh"} &` and sway hotkey bound to `alacritty --command bemenu-script`, launching via hotkey does everything as desired except launching a program like `firefox`, i.e. launch a terminal, run bemenu, and exit after selection. It just doesn't execute the selection.

If launched from the terminal instead of keybinding, it will detach from the terminal the bemenu script is running from and launch Firefox, but the terminal still remains. Not a bemenu problem so I'll have to look further when I get the time.

**Comment by crocket** [comment]
Execute

```
nohup setsid -f firefox [options...[ URL >/dev/null 2>&1
```

**Comment by Cloudef** [comment]
Ah, sorry I did not realize you were using bemenu instead of bemenu-run, --fork is bemenu-run specific command. There's something wrong with your launcher script in this case.
