### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by siyia2** [Cloudef/bemenu#124]
Ability to use left&right instead of up&down in selection of executable, especially if be-menu is setup in a horizontal style.

**Comment by Cloudef** [comment]
Use shift + left / right to select item, left / right moves cursor.

**Comment by siyia2** [comment]
nice thx i didnt see it in the description page

**Comment by cptMikky** [comment]
@Cloudef 
> Use shift + left / right to select item, left / right moves cursor.

In another issue you said you want to be as close to `dmenu` as possible. In `dmenu` left/right works slightly different: it moves the cursor only when it's not at the beginning/end of the typed text, otherwise it works as a selector - same as up/down.

I'd like to see this behavior in `bemenu` as well as I'm quite used to it. Custom keyboard mapping would of course be more useful but I understand there isn't much time to work on that.

Where's the line between "_as close to `dmenu` as possible_" and "_this is `bemenu` design decision even though it differs from `dmenu`_" ?

**Comment by Cloudef** [comment]
Note that we also support terminal, and on terminal not all the keybindings can be used. I'd like to have custom keybindings but this will need major refactor of the codebase.

**Comment by cptMikky** [comment]
Not sure why this keybinding can't be supported on terminal. Especially if it behaves like `dmenu`, that is, Left/Right moves cursor first and when the cursor is on either edge, move selection in menu.
