### ISSUE TITLE
the center flag doesn't change behaviour at all on wayland via bemenu-wayland backend

### ISSUE THREAD

**Issue by MonAaraj** [Cloudef/bemenu#223]
I've been trying to see if bemenu could be used in center mode, but it seems like it is anything but easy currently;
ways of invoking it that i have been attempting are simply `echo -n "1\n2\n3\n" | bemenu --center` or using `bemenu -c` instead of `bemenu --center` (or just `bemenu-run --center`), but it does not make bemenu centered at all. 

also, another issue i have seen that isnt fixed yet is that the --center option isn't in the manpage, only in the help response

bemenu version: 0.6.4
my distribution is Artix Linux

**Comment by Cloudef** [comment]
The actual placement of the window is done by compositor. Bemenu only sets hints on wayland: https://github.com/Cloudef/bemenu/blob/9cac33857d01d6f342eb54f3b31e8b192ef08563/lib/renderers/wayland/window.c#L217

**Comment by MonAaraj** [comment]
huh, i see. i use the river compositor, so i assume that has something to do with this not functioning?

**Comment by Cloudef** [comment]
Maybe, if I understood this code correctly https://github.com/riverwm/river/blob/c1d985ac2985b985aa8848490a0fab4fe8403dba/river/Output.zig#L338-L362 river does not handle the anchors as bitflags, but instead as single value. So it will only work for single anchor at time.

**Comment by ifreund** [comment]
Hey, author of river here.

I see `bemenu` setting an anchor value of `13` in WAYLAND_DEBUG logs, which is `left | top | right`. It's not terribly explicit in the layer shell protocol xml how the compositor should handle this, I think placing the bar at the top of the screen and stretching it to the full with of the screen if the client request a `0` width value is reasonable, and what river currently does.

In order to get river to center the layer shell client vertically as I believe is desired here, the anchor should be set to `left | right` or `12` on the wire.

I just tested this using the wlroots layer shell example client and things seem to work as I intended them.

Let me know if you have any questions!

**Comment by Cloudef** [comment]
Hmm, according it should be setting all bits: https://github.com/Cloudef/bemenu/blob/9cac33857d01d6f342eb54f3b31e8b192ef08563/lib/renderers/wayland/window.c#L217

ping @llunacb @stacyharper

**Comment by stacyharper** [comment]
o_O It seems to works perfectly here 

![screenshot of centered bemenu on sway](https://dav.missbanal.net/5542aa9d-be1b-4cf5-9da0-9a275512b16c.png)

I am missing something ?

**Comment by Cloudef** [comment]
Not sure where those extraneous set_anchor calls come from, reading the code it seems to protect itself pretty well from setting same align twice. At most it should be doing 2 calls. That might be worth debugging.

**Comment by stacyharper** [comment]
btw: I fixed recently wlroots to ignore concurrent calls as set_anchor if the anchor already is what it got. So multiple calls can be ignored

https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/8e566f716c464d886f1aed7e57b5bf26c3502426#a2d0a37683b2a7576f61a4c258827aefb459771d_129_136

**Comment by MonAaraj** [comment]
hello! I've tested the new river commit and it works perfectly! Thank you so much and I'm very sorry for submitting this issue to the wrong place!
