### ISSUE TITLE
Search for libncursesw on Debian/Ubuntu

### ISSUE THREAD

**Issue by wdbw** [Cloudef/bemenu#26]
I had to pass -DCURSES_LIBRARY=/lib/x86_64-linux-gnu/libncursesw.so.5 to cmake when building bemenu on Ubuntu 16.04 (64-bit).

Otherwise, I get this error:

> bemenu-run 
> /usr/lib/bemenu/bemenu-renderer-curses.so: undefined symbol: get_wch

**Comment by Earnestly** [comment]
The findcurses.cmake script bemenu uses is looking for curses when bemenu should be looking for ncursesw.

**Comment by bpinto** [comment]
I'm having the same issue but the errors doesn't seem to come from incorrect library loading, could it be requiring a specific version of ncurses?

**Comment by Cloudef** [comment]
It might be better to scrap the cmake and use makefile + pkg-config instead. Cmake is utterly crap at finding stuff.

**Comment by Earnestly** [comment]
Yeah, with the availability of `pkg-config`, it makes a great deal of these autoconfiguration systems a bit moot

**Comment by marienz** [comment]
Adding `SET(CURSES_NEED_WIDE TRUE)` to `lib/renderers/curses/CMakeLists.txt` made it work here, but you need at least CMake 3.10 (from August 2017) for that. I'm not familiar with cmake, so not sure if something like "bundle FindCurses.cmake from current CMake with bemenu" makes any sense.

**Comment by prometheanfire** [comment]
had to do the same thing in gentoo, cmake 3.10 could work with the `SET(CURSES_NEED_WIDE TRUE)` though

**Comment by Cloudef** [comment]
Does setting -DCURSES_NEED_WIDE=TRUE from command line work?

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/5a4d364d50b9ca6907de11f201b451e22aa02b85
Should hopefully fix this now since pkg-config is used.

**Comment by marienz** [comment]
Effectively same problem. The GNUmakefile uses ` pkg-config --cflags-only-I ncurses` and `pkg-config --libs ncurses`, which (on a Gentoo system) pulls in headers for "narrow" curses and links to `-lcurses`. This triggers

```
lib/renderers/curses/curses.c: In function ‘poll_key’:
lib/renderers/curses/curses.c:297:5: warning: implicit declaration of function ‘get_wch’; did you mean ‘getch’? [-Wimplicit-function-declaration]
  297 |     get_wch((wint_t*)unicode);
      |     ^~~~~~~
      |     getch
```

during compilation, and `/usr/local/lib/bemenu/bemenu-renderer-curses.so: undefined symbol: get_wch` at runtime.

Using ncursesw instead of ncurses in both pkg-config invocations fixes this: it adds `-I/usr/include/ncursesw` (which contains the `curses.h` that defines `get_wch`) and links to `-lncursesw -ltinfow`.

It looks like how this is set up varies between distros... for example, Debian 10/Buster only has one set of headers, but it looks like it does have the same libncurses / libncursesw split. I don't know if the ncursesw pkg-config file is available everywhere.

**Comment by Cloudef** [comment]
ncursesw is what should be used anyways since we use get_wch. Arch just symlinks everything to ncursesw. I'll change that!

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/0d7e1aa9bdc482484c119bbb5f4f289da1d0fef8

**Comment by Cloudef** [comment]
If this doesn't work for all distros, then doing https://github.com/Cloudef/bemenu/issues/50 would get rid of all curses insanity.
