### ISSUE TITLE
Wayland rendering issues

### ISSUE THREAD

**Issue by stacyharper** [Cloudef/bemenu#274]
Hey there !

There already was some rendering issues and redraw problems with wayland backend. Some frame was not redrawn when necessary. This commit made things even worse for a reason I dont fully understand yet.

```patch
c7a5812 Fix missed renders on Wayland on temporally close events Joan Bruguera 2022-06-29 00:24
diff --git a/lib/renderers/wayland/wayland.c b/lib/renderers/wayland/wayland.c
index bc3d83d..0bf145e 100644
--- a/lib/renderers/wayland/wayland.c
+++ b/lib/renderers/wayland/wayland.c
@@ -26,7 +26,7 @@ render(struct bm_menu *menu)
 
     struct window *window;
     wl_list_for_each(window, &wayland->windows, link) {
-        if (menu->dirty && window->render_pending)
+        if (window->render_pending)
             bm_wl_window_render(window, wayland->display, menu);
     }
     wl_display_flush(wayland->display);

```

I think we need a deep digging to clean this up. I made a video presenting the current state with 0.6.8. I ~then show in the second part~ show in a first part how bemenu works with this patch:

```diff
diff --git a/lib/renderers/wayland/wayland.c b/lib/renderers/wayland/wayland.c
index 0bf145e..e96b6d6 100644
--- a/lib/renderers/wayland/wayland.c
+++ b/lib/renderers/wayland/wayland.c
@@ -26,7 +26,7 @@ render(struct bm_menu *menu)
 
     struct window *window;
     wl_list_for_each(window, &wayland->windows, link) {
-        if (window->render_pending)
+        if (menu->dirty || window->render_pending)
             bm_wl_window_render(window, wayland->display, menu);
     }
     wl_display_flush(wayland->display);
```

The video is here : https://tube.missbanal.net/w/rbi1mntpcG8CNk28PCNQdb

edit: the video actually show the patched version then the upstream one !

**Comment by Cloudef** [comment]
@joanbm

**Comment by joanbm** [comment]
Hmm, thank you for the video, it makes the issue very clear. I can't get any rendering problem while manually using the mouse&keyboard on a PC. But since I lack a touch device, I tried to send some sudden mouse moves with `swaymsg`, and it looks there are some rendering issues (half the events seem to be skipped). See this video:

https://user-images.githubusercontent.com/519004/177003484-8c71153f-5ec1-46d0-a992-e2821cab9c96.mp4

I will take a deeper look later to see if I can figure what's going on.

**Comment by joanbm** [comment]
I have found what caused the problem in my previous post, the way the event loop was ordered, it was possible that we set the dirty flag, then go to sleep (wait for events) without ever rendering or scheduling a render callback.

@stacyharper Any chance you could build and test those changes on your setup? They should hopefully fix the issue (or at least not make things any worse):
* https://github.com/joanbm/bemenu/commit/3b9584894a7e8d4fc53e999a5613d88262dadaf9
* https://github.com/joanbm/bemenu/commit/6afffe522eede15e91b160bd2fecc2b40ab3437c

**Comment by stacyharper** [comment]
> @stacyharper Any chance you could build and test those changes on your setup? They should hopefully fix the issue (or at least not make things any worse):

I tested those and confirm it works very nicely !

**Comment by stacyharper** [comment]
There is an issue with the very first frame rendered. It is not very visible on desktop but on pinephone it is ugly. I also made a vod to show this :

https://tube.missbanal.net/w/62645da7-5717-4e29-a413-f3b396a90731

Easy to solve ?

**Comment by joanbm** [comment]
Thanks for testing! Fixed with those updated commits:
* https://github.com/joanbm/bemenu/commit/1824486d92bec4b09aa9138e63818fdda0d2fb72
* https://github.com/joanbm/bemenu/commit/3c2d89825a8894d666e324e5b1ea558b5ea77ef9

(Cause: The first render needs to be done immediately, it can't be done on a frame callback because we don't yet have the surface for receiving any events. I had moved it outside the event loop because it looked simpler, but the menu is not yet fully initialized there and caused the issue.)
