### ISSUE TITLE
Blurry font rendering while using HiDPI scaling on wayland

### ISSUE THREAD

**Issue by timsn** [Cloudef/bemenu#38]
I have issues with the bemenu font rendering when HiDPI scaling (factor 2) is used on wayland. I'm using sway (version 1.0-beta.2-270-g1a1133dc) and bemenu (r262.799d8b9-1 according to the package version I installed from git) on Archlinux.
I also tried to set the backend specifically to wayland using the `BEMENU_BACKEND` env variable and using different ttf fonts and sizes. But with no success. The font appears very blurry in comparison to other applications.

**Comment by Cloudef** [comment]
Bemenu doesn't implement hidpi, patches welcome though.

**Comment by hexd0t** [comment]
I've managed to cobble something together that works for my usecase, but feels a bit hacky, both due to me never having worked with wayland before an not spending a huge amount of time understanding the bemenu code.
Since I don't have the time to actually flesh this out (for example, multiline isn't tested at all, since I don't use it), I won't do a pull request.

But if anyone wants to try if it works for them as well or use it as a starting point for implementing HighDPI handling for real, you can take a look at hexd0t/bemenu@c7ceb253ed88be40c83a0d7c5772945119c294fa

**Comment by Cloudef** [comment]
@hexd0t your code doesn't look bad at all, and it seems like it's on right track. I hope somebody can pick from it. Thank you. To support X, I guess some env variable could be used. I'm not sure if there's X extension (maybe xrandr?) for querying scale information.

**Comment by bitonic** [comment]
@hexd0t I can testify that your patch seems to work just fine -- thank you!
