### ISSUE TITLE
In vim mode dw causes deadlock

### ISSUE THREAD

**Issue by yuri-the-cockroach** [Cloudef/bemenu#414]
With vim bindings, in normal mode, if you try to do dw on the last(or only) word, you will get a dead-lock. The bemenu will freeze and won't do anything else. If there is at least a space after the word, it will work as intended.

**Comment by oversoul** [comment]
@yuri-the-cockroach  as far as i can tell the issue comes from

https://github.com/Cloudef/bemenu/blob/master/lib/vim.c#L152

the `filter_length` should be updated on each iteration.
deleting the character causes the `filter` value to change, but it compares against the old size.

i can make a pull request for this, if the maintainers think it's the right way to proceed.

**Comment by Cloudef** [comment]
That sounds like a correct solution. Feel free open a PR

**Comment by oversoul** [comment]
@Cloudef alright #419

**Comment by spyjetfayed** [comment]
I'm still facing the same issue, when there is no space at the end of a word bemenu freezes. Flipping the sequence of the while loops in `vim.c` `delete_word()` seems to fix it for me.

```
    while (menu->cursor < strlen(menu->filter) && !isspace(menu->filter[menu->cursor])) delete_char(menu);
    while (menu->cursor < strlen(menu->filter) && isspace(menu->filter[menu->cursor])) delete_char(menu);
```
to
```
    while (menu->cursor < strlen(menu->filter) && isspace(menu->filter[menu->cursor])) delete_char(menu);
    while (menu->cursor < strlen(menu->filter) && !isspace(menu->filter[menu->cursor])) delete_char(menu);
```
